useDotenv: true

service: amazon-bestsellers-api
frameworkVersion: "3"

custom:
  tableName: ${self:service}-bestsellers-${sls:stage}
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    TABLE_NAME: ${self:custom.tableName}
    INTERNAL_API_KEY: ${env:INTERNAL_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tableName}

plugins:
  - serverless-esbuild

functions:
  health:
    handler: src/handlers/health.health
    events:
      - httpApi:
          path: /health
          method: GET
  getBestsellers:
    handler: src/handlers/get-bestsellers.getBestsellers
    events: 
      - httpApi:
          path: /bestsellers
          method: GET
  getBestsellersByCategory:
    handler: src/handlers/get-bestsellers.getBestsellersByCategory
    events: 
      - httpApi:
          path: /bestsellers/{category}
          method: GET
  getFirstTopBestsellers:
    handler: src/handlers/get-bestsellers.getFirstTopBestsellers
    events:
      - httpApi:
          path: /bestsellers/first-top
          method: GET
  getBestsellersOverview:
    handler: src/handlers/get-bestsellers.getBestsellersOverview
    events:
      - httpApi:
          path: /bestsellers/overview
          method: GET
  refreshBestsellers:
    handler: src/handlers/refresh-bestsellers.refreshBestsellers
    events:
      - httpApi:
          path: /internal/bestsellers/refresh
          method: POST
resources:
  Resources:
    BestsellersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
